### ISSUE TITLE
Uninitialized variable options

### ISSUE THREAD

**Issue by setharnold** [lcp/urfkill#11]
Hello, cppcheck found a bug that may lead to a segmentation violation:
[src/urf-config.c:633]: (error) Uninitialized variable: options

https://github.com/lcp/urfkill/blob/master/src/urf-config.c#L610

options->key_control is assigned before options is allocated. In the best case this kills the program, though there's a chance that it will write garbage to unrelated memory.

If this branch is actually taken, it looks like there should be several nearly identical warning messages from this block and from get_dmi_info().

Thanks

**Comment by lcp** [comment]
Thanks! Just push the fix.
